#!/bin/bash

message1=`grep '^MOTIVO DEL COMMIT: ' "$1"`;
message2=`grep 'IMPLEMENTACION: ' "$1"`;

if [ -z $message1 ];then
	echo "El mensaje no tiene la sintaxis correcta";
	exit 1;
else
	if [ -z $message2 ];then         
		echo "El mensaje no tiene la sintaxis correcta";                
		exit 1;
	else
		echo "Mensaje con sintaxis correcta";
		exit 0;
	fi
fi
